# Site settings
title: IMAI Authentic Japanese Cuisine
description: > # this means to ignore newlines until "baseurl:"
  Authentic Japanese restaurant in Georgetown, Ontario Canada

baseurl: "/imai-website" # the subpath of your site, e.g. /blog
url: "https://logonoff.co" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - assets/sass
  - build.bat
  - CNAME
  - Gemfile
  - Gemfile.lock
  - jekyll.bat
  - package.json
  - readme.md
  - assets/js/tab.html

# Jekyll SEO
facebook:
  publisher: https://www.facebook.com/Imai-Japanese-Cuisine-919515488131536/

social:
  links:
    - https://www.facebook.com/Imai-Japanese-Cuisine-919515488131536/
    - https://www.instagram.com/imaijapanese/

seo:
  name: IMAI Authentic Japanese Cuisine
  type: Restaurant

# Plugin settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
