# Site settings
title: IMAI Authentic Japanese Cuisine
description: > # this means to ignore newlines until "baseurl:"
  Authentic Japanese restaurant in Georgetown, Ontario Canada

baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://www.imaigeorgetown.ca/" # the base hostname & protocol for your site
url: "http://imai-pilot.logonoff.co/" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
